import type { Metadata } from "next";
import PrivateLayout from '@/components/layout/PrivateLayout';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <PrivateLayout>
          {children}
        </PrivateLayout>
  );
}
